import {
  BmpToPdf,
  CompressPdf,
  ExcelToPdf,
  ExtractPdfPages,
  GrayScalePdf,
  JpgToPdf,
  MergePdf,
  OrganizePdf,
  PdfToPowerpoint,
  PdfToTiff,
  PdfToTxt,
  PdfToWord,
  PdfToZip,
  PdftoBmp,
  PdftoJpg,
  PdftoPng,
  PngToPdf,
  PowerpointToPdf,
  ProtectPdf,
  RemovePages,
  RepairPdf,
  RotatePdf,
  TiffToPdf,
  TxtToPdf,
  UnlockPdf,
  WordToPdf,
} from "@/components/icons/Icon";
import { useTranslation } from "next-i18next";
const useToolsData = () => {
  const { t } = useTranslation();

  const toolsData = {
    MergePDFTool: {
      key: "MergePDF",
      title: "Merge PDF",
      // description: t("common:tool_desc_merge_pdf"),
      description: "Merge multiple PDF files into a single PDF",
      href: "/merge-pdf",
      icon: MergePdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "MergedPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
    },

    RotatePDFTool: {
      key: "RotatePDF",
      title: "Rotate PDF",
      // description: t("common:tool_desc_rotate_pdf"),
      description: "Rotate one or all pages in your PDF",
      href: "/rotate-pdf-pages",
      icon: RotatePdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RotatePDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
    },

    RemovePDFPagesTool: {
      key: "RemovePDFPages",
      title: "Remove Pages",
      // description: t("common:tool_desc_remove_Pages"),
      description: "Remove one or multiple pages from your PDF",
      href: "/remove-pdf-pages",
      icon: RemovePages,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RemovePDFPages.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
    },

    OrganizePDFTool: {
      key: "OrganizePDF",
      title: "Organize PDF",
      // description: t("common:tool_desc_organize_pdf"),
      description: "Sort, delete and merge pages of your PDF file",
      href: "/organize-pdf-pages",
      icon: OrganizePdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_OrganizePDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
    },

    CompressPDFTool: {
      key: "CompressPDF",
      title: "Compress PDF",
      // description: t("common:tool_desc_compress_pdf"),
      description: "Reduce the size of your PDF without losing quality",
      href: "/compress-pdf",
      icon: CompressPdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_compressed.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/compress-pdf",
    },

    GrayscalePDFTool: {
      key: "GrayscalePDF",
      title: "Grayscale PDF",
      // description: t("common:tool_desc_grayscale_pdf"),
      description: "Convert Text and Images to grayscale in your PDF file",
      href: "/grayscale-pdf",
      icon: GrayScalePdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_grayscaled.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/grayscale-pdf",
    },

    ExtractPagesTool: {
      key: "ExtractPages",
      title: "Extract PDF Pages",
      // description: t("common:tool_desc_extract_pages"),
      description: "Get a PDF document containing only the desired pages",
      href: "/extract-pdf-pages",
      icon: ExtractPdfPages,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_ExtractPages.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/extract-pdf-pages",
    },

    RepairPDFTool: {
      key: "RepairPDF",
      title: "Repair PDF",
      // description: t("common:tool_desc_repair_pdf"),
      description: "Repair a damaged PDF and recover data",
      href: "/repair-pdf",
      icon: RepairPdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RepairPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/repair-pdf",
    },

    JPGToPDFTool: {
      key: "JPGToPDF",
      title: "JPG To PDF",
      // description: t("common:tool_desc_jpg_to_pdf"),
      description: "Convert JPG Images to PDF documents",
      href: "/jpg-to-pdf",
      icon: JpgToPdf,
      acceptedInputMimeType: "image/jpeg",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_JPGToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/jpg-to-pdf",
    },

    PNGToPDFTool: {
      key: "PNGToPDF",
      title: "PNG To PDF",
      // description: t("common:tool_desc_png_to_pdf"),
      description: "Convert PNG Images to PDF documents",
      href: "/png-to-pdf",
      icon: PngToPdf,
      acceptedInputMimeType: "image/png",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PNGToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/png-to-pdf",
    },

    BMPToPDFTool: {
      key: "BMPToPDF",
      title: "BMP To PDF",
      // description: t("common:tool_desc_bmp_to_pdf"),
      description: "Convert BMP Images to PDF documents",
      href: "/bmp-to-pdf",
      icon: BmpToPdf,
      acceptedInputMimeType: "image/bmp",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_JPGToBMP.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/bmp-to-pdf",
    },

    TIFFToPDFTool: {
      key: "TIFFToPDF",
      title: "TIFF To PDF",
      // description: t("common:tool_desc_tiff_to_pdf"),
      description: "Convert TIFF Images to PDF documents",
      href: "/tiff-to-pdf",
      icon: TiffToPdf,
      acceptedInputMimeType: "image/tiff",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_TIFFToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/tiff-thumbnail.png",
      URI: "/tiff-to-pdf",
    },

    WORDToPDFTool: {
      key: "WORDToPDF",
      title: "Word to PDF",
      // description: t("common:tool_desc_word_to_pdf"),
      description: "Convert Word documents to PDF Documents",
      href: "/word-to-pdf",
      icon: WordToPdf,
      acceptedInputMimeType:
        "application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_WORDToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/word-thumbnail.png",
      URI: "/word-to-pdf",
    },

    PPTXToPDFTool: {
      key: "PPTXToPDF",
      title: " Powerpoint To PDF ",
      // description: t("common:tool_desc_powerpoint_to_pdf"),
      description: "Convert Powerpoint presentations to PDF Documents",
      href: "/pptx-to-pdf",
      icon: PowerpointToPdf,
      acceptedInputMimeType:
        "application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PPTXToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/pptx-thumbnail.png",
      URI: "/pptx-to-pdf",
    },

    TXTToPDFTool: {
      key: "TXTToPDF",
      title: "TXT To PDF",
      // description: t("common:tool_desc_txt_to_pdf"),
      description: "Convert Text files to PDF Documents",
      href: "/txt-to-pdf",
      icon: TxtToPdf,
      acceptedInputMimeType: "text/plain",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_TXTToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/txt-thumbnail.png",
      URI: "/txt-to-pdf",
    },

    EXCELToPDFTool: {
      key: "EXCELToPDF",
      title: "Excel To PDF",
      // description: t("common:tool_desc_excel_to_pdf"),
      description: "Convert Excel spreadsheets to PDF documents",
      href: "/excel-to-pdf",
      icon: ExcelToPdf,
      acceptedInputMimeType:
        "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_EXCELToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/excel-thumbnail.png",
      URI: "/excel-to-pdf",
    },

    PDFToJPGTool: {
      key: "PDFToJPG",
      title: "PDF To JPG",
      // description: t("common:tool_desc_pdf_to_jpg"),
      description: "Convert PDF documents to JPG Images",
      href: "/pdf-to-jpg",
      icon: PdftoJpg,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToJPG.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-jpg",
    },

    PDFToPNGTool: {
      key: "PDFToPNG",
      title: "PDF To PNG",
      // description: t("common:tool_desc_pdf_to_png"),
      description: "Convert PDF documents to PNG Images",
      href: "/pdf-to-png",
      icon: PdftoPng,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToPNG.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-png",
    },

    PDFToBMPTool: {
      key: "PDFToBMP",
      title: "PDF To BMP",
      // description: t("common:tool_desc_pdf_to_bmp"),
      description: "Convert PDF documents to BMP Images",
      href: "/pdf-to-bmp",
      icon: PdftoBmp,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 10485760, //10MB = 10240KB (in binary) = 10485760 B (in binary),
      newFileNameSuffix: "_PDFToBMP.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-bmp",
    },

    PDFToTIFFTool: {
      key: "PDFToTIFF",
      title: "PDF To TIFF",
      // description: t("common:tool_desc_pdf_to_tiff"),
      description: "Convert PDF documents to TIFF Images",
      href: "/pdf-to-tiff",
      icon: PdfToTiff,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToTIFF.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-tiff",
    },

    PDFToWORDTool: {
      key: "PDFToWORD",
      title: "PDF To Word",
      description: "Convert PDF files to Word documents",
      href: "/pdf-to-word",
      icon: PdfToWord,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToWORD.docx",
      outputFileMimeType: "application/msword",
      thumbnailImageURL: "",
      URI: "/pdf-to-word",
    },

    PDFToPPTXTool: {
      key: "PDFToPPTX",
      title: "PDF To Powerpoint",
      // description: t("common:tool_desc_pdf_to_powerpoint"),
      description: "Convert PDF files to Powerpoint presentations",
      href: "/pdf-to-pptx",
      icon: PdfToPowerpoint,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToPPTX.pptx",
      outputFileMimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      thumbnailImageURL: "",
      URI: "/pdf-to-pptx",
    },

    PDFToTXTTool: {
      key: "PDFToTXT",
      title: "PDF To TXT",
      // description: t("common:tool_desc_pdf_to_txt"),
      description: "Convert PDF files to Text files",
      href: "/pdf-to-txt",
      icon: PdfToTxt,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToTXT.txt",
      outputFileMimeType: "text/plain",
      thumbnailImageURL: "",
      URI: "/pdf-to-txt",
    },

    PDFToZIPTool: {
      key: "PDFToZIP",
      title: "PDF To ZIP",
      // description: t("common:tool_desc_pdf_to_zip"),
      description: "Convert PDF files to ZIP file",
      href: "/pdf-to-zip",
      icon: PdfToZip,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: ".pdf",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "",
    },

    ProtectPDFTool: {
      key: "ProtectPDF",
      title: "Protect PDF",
      // description: t("common:tool_desc_unlock_pdf"),
      description: "Add a password and encrypt your PDF file",
      href: "/protect-pdf",
      icon: ProtectPdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_ProtectPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/protect-pdf",
    },

    UnlockPDFTool: {
      key: "UnlockPDF",
      title: "Unlock PDF",
      description: "Remove password from your protected PDF files",

      href: "/unlock-pdf",
      icon: UnlockPdf,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_UnlockPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/unlock-pdf",
    },
  };

  return toolsData;
};

export default useToolsData;
