import {
  FileEarmarkExcel,
  FileEarmarkPdf,
  FileEarmarkPpt,
  FileEarmarkWord,
  FileEarmarkZip,
  FiletypeBmp,
  FiletypeJpg,
  FiletypePng,
  FiletypeTiff,
  FiletypeTxt,
  Lock,
  Unlock,
} from "react-bootstrap-icons";
import { useTranslation } from "next-i18next";

import {
  BmpToPdfIndex,
  CompressPdfIndex,
  ExcelToPdfIndex,
  ExtractPdfPageIndex,
  GrayScalePdfIndex,
  JpgToPdfIndex,
  MergePdfIndex,
  OrganizePdfIndex,
  PdfToPowerpointIndex,
  PdfToTiffIndex,
  PdfToTxtIndex,
  PdfToWordIndex,
  PdfToZIpIndex,
  PdftoBmpIndex,
  PdftoJpgIndex,
  PdftoPngIndex,
  PngToPdfIndex,
  PowerpointToPdfIndex,
  ProtectPdfIndex,
  RemovePagesIndex,
  RepairPdfIndex,
  RotatePdfIndex,
  TiffToPdfIndex,
  TxtToPdfIndex,
  UnlockPdfIndex,
  WordToPdfIndex,
} from "@/components/icons/indexIcon";
const useToolsIndexData = () => {
  const { t } = useTranslation();

  const toolsData = {
    MergePDFTool: {
      key: "MergePDF",
      // title: t("common:tool_name_merge_pdf"),
      title: "Merge PDF",
      // description: t("common:tool_desc_merge_pdf"),
      description: "Merge multiple PDF files into a single PDF",
      href: "/merge-pdf",
      icon: MergePdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "MergedPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
      color: "#EE1B22",
    },

    RotatePDFTool: {
      key: "RotatePDF",
      // title: t("common:tool_name_rotate_pdf"),
      title: "Rotate PDF",
      // description: t("common:tool_desc_rotate_pdf"),
      description: "Rotate one or all pages in your PDF",
      href: "/rotate-pdf-pages",
      icon: RotatePdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RotatePDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
      color: "#EE1B22",
    },

    RemovePDFPagesTool: {
      key: "RemovePDFPages",
      // title: t("common:tool_name_remove_Pages"),
      title: "Remove Pages",
      // description: t("common:tool_desc_remove_Pages"),
      description: "Remove one or multiple pages from your PDF",
      href: "/remove-pdf-pages",
      icon: RemovePagesIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RemovePDFPages.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
      color: "#EE1B22",
    },

    OrganizePDFTool: {
      key: "OrganizePDF",
      // title: t("common:tool_name_organize_pdf"),
      title: "Organize PDF",
      // description: t("common:tool_desc_organize_pdf"),
      description: "Sort, delete and merge pages of your PDF file",
      href: "/organize-pdf-pages",
      icon: OrganizePdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_OrganizePDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "",
      color: "#EE1B22",
    },

    CompressPDFTool: {
      key: "CompressPDF",
      title: t("common:tool_name_compress_pdf"),
      title: "Compress PDF",
      // description: t("common:tool_desc_compress_pdf"),
      description: "Reduce the size of your PDF without losing quality",
      href: "/compress-pdf",
      icon: CompressPdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_compressed.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/compress-pdf",
      color: "#EE1B22",
    },

    GrayscalePDFTool: {
      key: "GrayscalePDF",
      // title: t("common:tool_name_grayscale_pdf"),
      title: "Grayscale PDF",
      // description: t("common:tool_desc_grayscale_pdf"),
      description: "Convert Text and Images to grayscale in your PDF file",
      href: "/grayscale-pdf",
      icon: GrayScalePdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_grayscaled.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/grayscale-pdf",
      color: "#EE1B22",
    },

    ExtractPagesTool: {
      key: "ExtractPages",
      // title: t("common:tool_name_extract_pages"),
      title: "Extract PDF Pages",
      // description: t("common:tool_desc_extract_pages"),
      description: "Get a PDF document containing only the desired pages",
      href: "/extract-pdf-pages",
      icon: ExtractPdfPageIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_ExtractPages.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/extract-pdf-pages",
      color: "#EE1B22",
    },

    RepairPDFTool: {
      key: "RepairPDF",
      // title: t("common:tool_name_repair_pdf"),
      title: "Repair PDF",
      // description: t("common:tool_desc_repair_pdf"),
      description: "Repair a damaged PDF and recover data",
      href: "/repair-pdf",
      icon: RepairPdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_RepairPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/repair-pdf",
      color: "#EE1B22",
    },

    JPGToPDFTool: {
      key: "JPGToPDF",
      // title: t("common:tool_name_jpg_to_pdf"),
      title: "JPG To PDF",
      // description: t("common:tool_desc_jpg_to_pdf"),
      description: "Convert JPG Images to PDF documents",
      href: "/jpg-to-pdf",
      icon: JpgToPdfIndex,
      acceptedInputMimeType: "image/jpeg",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_JPGToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/jpg-to-pdf",
      color: "#14A085",
    },

    PNGToPDFTool: {
      key: "PNGToPDF",
      // title: t("common:tool_name_png_to_pdf"),
      title: "PNG To PDF",
      // description: t("common:tool_desc_png_to_pdf"),
      description: "Convert PNG Images to PDF documents",
      href: "/png-to-pdf",
      icon: PngToPdfIndex,
      acceptedInputMimeType: "image/png",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PNGToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/png-to-pdf",
      color: "#9C0DDF",
    },

    BMPToPDFTool: {
      key: "BMPToPDF",
      // title: t("common:tool_name_bmp_to_pdf"),
      title: "BMP To PDF",
      // description: t("common:tool_desc_bmp_to_pdf"),
      description: "Convert BMP Images to PDF documents",
      href: "/bmp-to-pdf",
      icon: BmpToPdfIndex,
      acceptedInputMimeType: "image/bmp",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_JPGToBMP.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/bmp-to-pdf",
      color: "#C9940D",
    },

    TIFFToPDFTool: {
      key: "TIFFToPDF",
      // title: t("common:tool_name_tiff_to_pdf"),
      title: "TIFF To PDF",
      description: t("common:tool_desc_tiff_to_pdf"),
      description: "Convert TIFF Images to PDF documents",
      href: "/tiff-to-pdf",
      icon: TiffToPdfIndex,
      acceptedInputMimeType: "image/tiff",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_TIFFToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/tiff-thumbnail.png",
      URI: "/tiff-to-pdf",
      color: "#D60DDA",
    },

    WORDToPDFTool: {
      key: "WORDToPDF",
      // title: t("common:tool_name_word_to_pdf"),
      title: "Word to PDF",
      // description: t("common:tool_desc_word_to_pdf"),
      description: "Convert Word documents to PDF Documents",
      href: "/word-to-pdf",
      icon: WordToPdfIndex,
      acceptedInputMimeType:
        "application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_WORDToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/word-thumbnail.png",
      URI: "/word-to-pdf",
      color: "#0263D1",
    },

    PPTXToPDFTool: {
      key: "PPTXToPDF",
      // title: t("common:tool_name_powerpoint_to_pdf"),
      title: " Powerpoint To PDF ",
      // description: t("common:tool_desc_powerpoint_to_pdf"),
      description: "Convert Powerpoint presentations to PDF Documents",
      href: "/pptx-to-pdf",
      icon: PowerpointToPdfIndex,
      acceptedInputMimeType:
        "application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PPTXToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/pptx-thumbnail.png",
      URI: "/pptx-to-pdf",
      color: "#E03303",
    },

    TXTToPDFTool: {
      key: "TXTToPDF",
      // title: t("common:tool_name_txt_to_pdf"),
      title: "TXT To PDF",
      // description: t("common:tool_desc_txt_to_pdf"),
      description: "Convert Text files to PDF Documents",
      href: "/txt-to-pdf",
      icon: TxtToPdfIndex,
      acceptedInputMimeType: "text/plain",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_TXTToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/txt-thumbnail.png",
      URI: "/txt-to-pdf",
      color: "#0BB1D5",
    },

    EXCELToPDFTool: {
      key: "EXCELToPDF",
      // title: t("common:tool_name_excel_to_pdf"),
      title: "Excel To PDF",
      // description: t("common:tool_desc_excel_to_pdf"),
      description: "Convert Excel spreadsheets to PDF documents",
      href: "/excel-to-pdf",
      icon: ExcelToPdfIndex,
      acceptedInputMimeType:
        "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_EXCELToPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "/img/excel-thumbnail.png",
      URI: "/excel-to-pdf",
      color: "#00733B",
    },

    PDFToJPGTool: {
      key: "PDFToJPG",
      // title: t("common:tool_name_pdf_to_jpg"),
      title: "PDF To JPG",
      // description: t("common:tool_desc_pdf_to_jpg"),
      description: "Convert PDF documents to JPG Images",
      href: "/pdf-to-jpg",
      icon: PdftoJpgIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToJPG.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-jpg",
      color: "#14A085",
    },

    PDFToPNGTool: {
      key: "PDFToPNG",
      // title: t("common:tool_name_pdf_to_png"),
      title: "PDF To PNG",
      // description: t("common:tool_desc_pdf_to_png"),
      description: "Convert PDF documents to PNG Images",
      href: "/pdf-to-png",
      icon: PdftoPngIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToPNG.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-png",
      color: "#9C0DDF",
    },

    PDFToBMPTool: {
      key: "PDFToBMP",
      // title: t("common:tool_name_pdf_to_bmp"),
      title: "PDF To BMP",
      // description: t("common:tool_desc_pdf_to_bmp"),
      description: "Convert PDF documents to BMP Images",
      href: "/pdf-to-bmp",
      icon: PdftoBmpIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 10485760, //10MB = 10240KB (in binary) = 10485760 B (in binary),
      newFileNameSuffix: "_PDFToBMP.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-bmp",
      color: "#C9940D",
    },

    PDFToTIFFTool: {
      key: "PDFToTIFF",
      // title: t("common:tool_name_pdf_to_tiff"),
      title: "PDF To TIFF",
      // description: t("common:tool_desc_pdf_to_tiff"),
      description: "Convert PDF documents to TIFF Images",
      href: "/pdf-to-tiff",
      icon: PdfToTiffIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToTIFF.zip",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "/pdf-to-tiff",
      color: "#D60DDA",
    },

    PDFToWORDTool: {
      key: "PDFToWORD",
      // title: t("common:tool_name_pdf_to_word"),
      title: "PDF To Word",
      description: "Convert PDF files to Word documents",
      href: "/pdf-to-word",
      icon: PdfToWordIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToWORD.docx",
      outputFileMimeType: "application/msword",
      thumbnailImageURL: "",
      URI: "/pdf-to-word",
      color: "#0263D1",
    },

    PDFToPPTXTool: {
      key: "PDFToPPTX",
      // title: t("common:tool_name_pdf_to_powerpoint"),
      title: "PDF To Powerpoint",
      // description: t("common:tool_desc_pdf_to_powerpoint"),
      description: "Convert PDF files to Powerpoint presentations",
      href: "/pdf-to-pptx",
      icon: PdfToPowerpointIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToPPTX.pptx",
      outputFileMimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      thumbnailImageURL: "",
      URI: "/pdf-to-pptx",
      color: "#E03303",
    },

    PDFToTXTTool: {
      key: "PDFToTXT",
      // title: t("common:tool_name_pdf_to_txt"),
      title: "PDF To TXT",
      // description: t("common:tool_desc_pdf_to_txt"),
      description: "Convert PDF files to Text files",
      href: "/pdf-to-txt",
      icon: PdfToTxtIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_PDFToTXT.txt",
      outputFileMimeType: "text/plain",
      thumbnailImageURL: "",
      URI: "/pdf-to-txt",
      color: "#0BB1D5",
    },

    PDFToZIPTool: {
      key: "PDFToZIP",
      // title: t("common:tool_name_pdf_to_zip"),
      title: "PDF To ZIP",
      // description: t("common:tool_desc_pdf_to_zip"),
      description: "Convert PDF files to ZIP file",
      href: "/pdf-to-zip",
      icon: PdfToZIpIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: ".pdf",
      outputFileMimeType: "application/zip",
      thumbnailImageURL: "",
      URI: "",
      color: "#ffb11f",
    },

    ProtectPDFTool: {
      key: "ProtectPDF",
      title: t("common:tool_name_protect_pdf"),
      description: t("common:tool_desc_protect_pdf"),
      href: "/protect-pdf",
      icon: ProtectPdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_ProtectPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/protect-pdf",
      color: "#EE1B22",
    },

    UnlockPDFTool: {
      key: "UnlockPDF",
      // title: t("common:tool_name_unlock_pdf"),
      title: "Protect PDF",
      // description: t("common:tool_desc_unlock_pdf"),
      description: "Add a password and encrypt your PDF file",
      href: "/unlock-pdf",
      icon: UnlockPdfIndex,
      acceptedInputMimeType: "application/pdf",
      acceptedInputFileMaxSize: 26214400, //25MB = 25600 KB (in binary) = 26214400 B (in binary),
      newFileNameSuffix: "_UnlockPDF.pdf",
      outputFileMimeType: "application/pdf",
      thumbnailImageURL: "",
      URI: "/unlock-pdf",
      color: "#EE1B22",
    },
  };

  return toolsData;
};

export default useToolsIndexData;
